alias pip=pip3

if [[ "$OSTYPE" == "darwin"* ]]; then
  alias vim="mvim -v" # use macvim on macos
  eval "$(/opt/homebrew/bin/brew shellenv)"
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi
